### PR TITLE
fix for multiple command line parameters

### PR DESCRIPTION
**Pull request by atwayne**
Simple fix for #4

### CODE REVIEW

**Comment by davidwhitney** [comment]
:+1: I like this, I'll get it merged and up on nuget this evening. Cheers :)

**Comment by atwayne** [comment]
@davidwhitney ,can this be merged?

**Comment by davidwhitney** [comment]
Published as SimpleServices.2.0.16.0 thanks :)

**Comment by atwayne** [comment]
Great. Cheers ;)

**Pull request merged**
